apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitlab
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/alterus-io/umbrella.git
    targetRevision: master
    path: gitlab
    helm:
      values: |-
        global:
          edition: ce

          hosts:
            domain: atoy.lol

        certmanager-issuer:
          email: atoy3731@gmail.com
  destination:
    server: https://kubernetes.default.svc
    namespace: gitlab
  syncPolicy:
    automated:
      prune: true