apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://gitlab.com/gitlab-org/charts/gitlab.git
    targetRevision: master
    path: charts/gitlab
    helm:
      values: |-
        global:
          ingress:
            class: nginx

          hosts:
            domain: atoy.lol

        nginx-ingress:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true