apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/helm/charts.git
    targetRevision: master
    path: stable/jenkins
    helm:
      values: |-
        master:
          ingress:
            enabled: true
            hostName: jenkins.atoy.lol

        persistence:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: jenkins
  syncPolicy:
    automated:
      prune: true