apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-secret-webhook
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/alterus-io/cert-manager-webhook.git
    targetRevision: master
    path: chart
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true