apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jetstack/cert-manager.git
    targetRevision: v0.15.0
    path: deploy/charts/cert-manager
    helm:
      values: |
        installCRDs: "true"
        cainjector:
          image:
            tag: "v0.15.0"
        webhook:
          image:
            tag: "v0.15.0"
        image:
          tag: "v0.15.0"
        podDnsConfig:
          nameservers:
            - "1.1.1.1"
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true